// Interface costatnts 
export const TOGGLE_PROJECT_FORM = 'OPEN_PROJECT_FORM'
export const TOGGLE_TASK_FORM = 'OPEN_TASK_FORM'
export const TOGGLE_IS_REGISTERED = 'TOGGLE_IS_REGISTERED'
export const TOGGLE_PROJECT_EDIT = 'TOGGLE_EDIT'
export const TOGGLE_TASK_EDIT = 'TOGGLE_TASK_EDIT'

export const TOGGLE_IS_LOADING = 'TOGGLE_IS_LOADING'
export const TOGGLE_IS_MODAL_LOADING = 'TOGGLE_IS_MODAL_LOADING'

// Alert Constants
export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

// User Constants
export const CREATE_USER_BEGIN = 'CREATE__USER_BEGIN'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR'


export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const GET_A_USER_BEGIN = 'GET_A_USER_BEGIN'
export const GET_A_USER_SUCCESS = 'GET_A_USER_SUCCESS'
export const GET_A_USER_ERROR = 'GET_A_USER_ERROR'

// Project Constants
export const CREATE_PROJECT_BEGIN = 'CREATE_PROJECT_BEGIN'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR'

export const GET_ALL_RECENT_PROJECTS_BEGIN = 'GET_ALL_RECENT_PROJECTS_BEGIN'
export const GET_ALL_RECENT_PROJECTS_SUCCESS = 'GET_ALL_RECENT_PROJECTS_SUCCESS'
export const GET_ALL_RECENT_PROJECTS_ERROR = 'GET_ALL_RECENT_PROJECTS_ERROR'

export const GET_ALL_PROJECTS_BEGIN = 'GET_ALL_PROJECTS_BEGIN'
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS'
export const GET_ALL_PROJECTS_ERROR = 'GET_ALL_PROJECTS_ERROR'

export const GET_ACTIVE_PROJECT_TITLE = 'GET_ACTIVE_PROJECT_TITLE'

export const GET_MY_RECENT_PROJECTS_BEGIN = 'GET_MY_RECENT_PROJECTS_BEGIN'
export const GET_MY_RECENT_PROJECTS_SUCCESS = 'GET_MY_RECENT_PROJECTS_SUCCESS'
export const GET_MY_RECENT_PROJECTS_ERROR = 'GET_MY_RECENT_PROJECTS_ERROR'

export const GET_MY_COMPLETED_PROJECTS_BEGIN = 'GET_MY_COMPLETED_PROJECTS_BEGIN'
export const GET_MY_COMPLETED_PROJECTS_SUCCESS = 'GET_MY_COMPLETED_PROJECTS_SUCCESS'
export const GET_MY_COMPLETED_PROJECTS_ERROR = 'GET_MY_COMPLETED_PROJECTS_ERROR'


export const SET_PROJECT_AS_COMPLETED_BEGIN =  'SET_PROJECT_AS_COMPLETED_BEGIN'
export const SET_PROJECT_AS_COMPLETED_SUCCESS =  'SET_PROJECT_AS_COMPLETED_SUCCESS'
export const SET_PROJECT_AS_COMPLETED_ERROR =  'SET_PROJECT_AS_COMPLETED_ERROR'

export const EDIT_PROJECT_BEGIN = 'DELETE_PROJECT_BEGIN'
export const EDIT_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const EDIT_PROJECT_ERROR = 'DELETE_PROJECT_ERROR'

export const DELETE_PROJECT_BEGIN = 'DELETE_PROJECT_BEGIN'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR'

export const GET_PROJECT_DETAILS_BEGIN = 'GET_PROJECT_DETAILS_BEGIN'
export const GET_PROJECT_DETAILS_SUCCESS = 'GET_PROJECT_DETAILS_SUCCESS'
export const GET_PROJECT_DETAILS_ERROR = 'GET_PROJECT_DETAILS_ERROR'


// Task Constants
export const CREATE_TASK_BEGIN = 'CREATE_STASK_BEGIN'
export const CREATE_TASK_SUCCESS = 'CREATE_STASK_SUCCESS'
export const CREATE_TASK_ERROR = 'CREATE_STASK_ERROR'

export const GET_MY_TODO_TASKS_BEGIN = 'GET_MY_TODO_TASKS_BEGIN'
export const GET_MY_TODO_TASKS_SUCCESS = 'GET_MY_TODO_TASKS_SUCCESS'
export const GET_MY_TODO_TASKS_ERROR = 'GET_MY_TODO_TASKS_ERORR'

export const GET_MY_INPROGRESS_TASKS_BEGIN = 'GET_MY_INPROGRESS_TASKS_BEGIN'
export const GET_MY_INPROGRESS_TASKS_SUCCESS = 'GET_MY_INPROGRESS_TASKS_SUCCESS'
export const GET_MY_INPROGRESS_TASKS_ERROR = 'GET_MY_INPROGRESS_TASKS_ERROR'

export const GET_MY_COMPLETED_TASKS_BEGIN = 'GET_MY_COMPLETED_TASKS_BEGIN'
export const GET_MY_COMPLETED_TASKS_SUCCESS = 'GET_MY_COMPLETED_TASKS_SUCCESS'
export const GET_MY_COMPLETED_TASKS_ERROR = 'GET_MY_COMPLETED_TASKS_ERROR'

export const UPDATE_TASK_STATUS_BEGIN =  'UPDATE_TASK_STATUS_BEGIN'
export const UPDATE_TASK_STATUS_SUCCESS =  'UPDATE_TASK_STATUS_SUCCESS'
export const UPDATE_TASK_STATUS_ERROR =  'UPDATE_TASK_STATUS_ERROR'

export const GET_TASK_DETAILS = 'GET_TASK_DETAILS'

export const DELETE_TASK_BEGIN = 'DELETE_PROJECT_BEGIN'
export const DELETE_TASK_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_TASK_ERROR = 'DELETE_PROJECT_ERROR'

export const EDIT_TASK_BEGIN = 'EDIT_TASK_BEGIN'
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS'
export const EDIT_TASK_ERROR = 'EDIT_TASK_ERROR'
